services:
  - type: web
    name: pdf-tool-api
    runtime: docker
    repo: https://github.com/langlangforxsn/PDFtool
    branch: main
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
